[project]
name = "tn-lottery"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "lxml>=6.0.2",
    "numpy>=2.2.3",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "rich-click>=1.9.4",
]

[project.scripts]
tn-lottery = "tn_lottery.cli:cli"
