[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --cov=tn_lottery
    --cov-report=html
    --cov-report=term-missing
    -v
